spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vhr?useSSL=true&useUnicode=true&CharacterEncoding=UTF-8&serverTimezon=Asia/Shanghai
    username: root
    password: 2017liyuan@


